CREATE TABLE Author (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL
);


CREATE TABLE Publisher (
	id INTEGER PRIMARY KEY, 
	name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Book (
	id INTEGER PRIMARY KEY, 
	title TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS BookAuthor (
	id INTEGER PRIMARY KEY, 
	book_id INTEGER NOT NULL REFERENCES Book(id),
	author_id INTEGER NOT NULL REFERENCES Author (id)
);

CREATE TABLE IF NOT EXISTS BookInstance (
	id INTEGER PRIMARY KEY, 
	book_id INTEGER NOT NULL REFERENCES Book (id),
	publisher_id INTEGER NOT NULL REFERENCES Publisher (id),
	year INTEGER NOT NULL, 
	isbn TEXT NOT NULL
);
